name: Run Unittests
description: Runs unittests

inputs:
  python:
    default: '3.9' # Used for branches
    description: 'Python version'

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v3

    - name: Retrieve the environment and the River build
      uses: ./.github/actions/retrieve-env
      with:
        python: ${{ inputs.python }}

    - name: Cache River datasets
      uses: actions/cache@v2
      with:
        path: ~/river_data
        key: ${{ runner.os }}

    - name: Cache scikit-learn datasets
      uses: actions/cache@v2
      with:
        path: ~/scikit_learn_data
        key: ${{ runner.os }}

    - name: Download datasets
      shell: bash
      run: |
        source ~/.venv/bin/activate
        python -c "from river import datasets; datasets.CreditCard().download(); datasets.Elec2().download()"

    - name: pytest [Branch]
      if: github.event_name == 'pull_request'
      shell: bash
      run: |
        source ~/.venv/bin/activate
        pytest --durations=10 -n logical # Run pytest on all logical CPU cores

    - name: pytest [Main]
      if: github.event_name == 'push'
      shell: bash
      run: |
        source ~/.venv/bin/activate
        pytest -m "not datasets" --durations=10 -n logical # Run pytest on all logical CPU cores