name: Create Environment
description: Retrieves Python

inputs:
  python:
    description: 'Python version'

runs:
  using: "composite"


  steps:
    - name: Retrieve the Python environment
      uses: actions/cache/restore@v3
      id: retrieve-venv
      with:
        path: |
          ~/.venv
          ~/.local/bin
        key: ${{ github.run_id }}-venv-${{ runner.os }}-${{ inputs.python }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.python }}-venv

    - name: Retrieve River
      uses: actions/cache/restore@v3
      id: retrieve-river
      with:
        path: ${{ github.workspace }}
        key: river-build-${{ github.run_id }}-${{ runner.os }}-${{ inputs.python }}

    - name: Adjust workspace ownership
      shell: bash
      run: chown -hR $USER ${{ github.workspace }}
