name: build-river
on:
  workflow_call:

jobs:
  build_river:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10" ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: set up rust
        if: matrix.os != 'ubuntu-latest'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=nightly --profile=minimal -y && rustup show
        if: matrix.os == 'ubuntu-latest'

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Cache the Python environment
        uses: actions/cache@v3
        id: cache-venv
        with:
          path: |
            ~/.venv
          key: ${{ matrix.os }}-${{ matrix.python }}-venv-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ github.run_id }}-venv-${{ matrix.os }}-${{ matrix.python }}
            ${{ matrix.os }}-${{ matrix.python }}-venv-

      - name: Install Python dependencies
        if: ${{ steps.cache-venv.outputs.cache-hit != 'true' }}
        run: |
          python -m pip install --upgrade pip
          python -m venv ~/.venv
          source ~/.venv/bin/activate
          pip install wheel
          pip install scikit-learn sqlalchemy
          pip install pytest-xdist[psutil]
          
      - name: Build River
        run: |
          source ~/.venv/bin/activate
          pip install -e ".[dev]"

      - uses: actions/cache/save@v3
        id: cache-river
        with:
          path: ${{ github.workspace }}
          key: river-build-${{ github.run_id }}-${{ matrix.os }}-${{ matrix.python }}