name: build-river
on:
  workflow_call:

jobs:
  build_river:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10" ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: set up rust
        if: matrix.os != 'ubuntu-latest'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=nightly --profile=minimal -y && rustup show
        if: matrix.os == 'ubuntu-latest'

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Cache the Python environment
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: ~/.venv
          key: ${{ matrix.os }}-${{ matrix.python }}-venv-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.python }}-venv-

      - name: Install Python dependencies
        if: ${{ steps.cache-venv.outputs.cache-hit != 'true' }}
        run: |
          python -m pip install --upgrade pip
          python -m venv ~/.venv
          source ~/.venv/bin/activate
          pip install wheel
          pip install scikit-learn sqlalchemy
          pip install pytest-xdist[psutil]
          
      - name: Build River
        run: |
          source ~/.venv/bin/activate
          pip install -e ".[dev]"

      - name: Compress the Virtual Environment
        run: tar -czf ~/venv.tar.gz ~/.venv

      - name: Compress the Workspace
        run: tar -czf ~/river.tar.gz $GITHUB_WORKSPACE # The entire workspace is saved (It should only contain river anyway...)

#      - name: Archive Venv artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: venv-${{ github.run_id }}-${{ matrix.os }}-${{ matrix.python }} # Artifacts should only be used within runs!
#          path: ~/venv.tar.gz
#          retention-days: 1
#          if-no-files-found: error

      - name: Archive River artifact
        uses: actions/upload-artifact@v3
        with:
          name: river-build-${{ github.run_id }}-${{ matrix.os }}-${{ matrix.python }} # Artifacts should only be used within runs!
          path: |
            ~/venv.tar.gz
            ~/river.tar.gz
          retention-days: 1
          if-no-files-found: error