name: unit-tests

on:
  workflow_call:

jobs:


  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Retrieve the environment and the River build
        uses: ./.github/actions/retrieve-env
        with:
          python: 3.9

      - run: ls -la ${{github.workspace}}

      - name: Install Ubuntu dependencies
        run: sudo apt-get install graphviz pandoc

      - name: Build docs
        run: |
          source ~/.venv/bin/activate
          make doc

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1

      - name: Deploy docs
        env:
          GH_TOKEN: ${{ secrets.GitHubToken }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config pull.rebase false
          git add --all
          git commit -m "Release dev docs" --allow-empty
          git fetch
          git checkout gh-pages
          git pull
          git checkout main
#          mike deploy dev --push --remote https://github.com/online-ml/river.git
