name: shared-builds

on:
  push:
    branches:
      - main
      - feature/new_dep_jobs_workflows

  pull_request:
    branches:
      - "*"

jobs:
  build-river:
    uses: ./.github/workflows/build-river.yml

  unit-tests:
    needs: build-river
    uses: ./.github/workflows/unit-tests.yml

  branch-docs:
    if: github.event_name == 'push'
    needs: unit-tests # The workflow will actually update docs, so it's best to wait for unit tests too.
    uses: ./.github/workflows/docs.yml
    secrets: inherit

  dev-docs:
    if: github.event_name == 'pull_request'
    needs: build-river # The workflow will only build docs, so no need to wait for unit tests.
    uses: ./.github/workflows/docs.yml

