name: shared-builds

on:
  push:
    branches:
      - main
      - feature/new_dep_jobs_workflows

  pull_request:
    branches:
      - "*"

jobs:
  build-river:
    uses: ./.github/workflows/build-river.yml

  unit-tests:
    if: github.event_name == 'push'
    needs: build-river
    uses: ./.github/workflows/unit-tests.yml

  docs:
    runs-on: "ubuntu-latest"
    needs: build-river

    steps:
      - uses: actions/checkout@v3

      - name: Build Docs
        uses: ./.github/actions/docs
        with:
          github-token: ${{ secrets.GitHubToken }}



