name: unit-tests

on:
  push:
    branches:
      - main
      - feature/dependent_actions

jobs:
  call_river_build:
    strategy:
      fail-fast: false
      matrix:
        python: [ "3.10" ] #[3.8, 3.9, "3.10"]
        os: [ ubuntu-latest, macos-latest ]

    uses: ./.github/workflows/build-river.yml
    with:
      os: ${{ matrix.os }}
      python: ${{ matrix.python }}

  test:
    needs: call_river_build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10"] #[3.8, 3.9, "3.10"]
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Retrieve Python Dependencies
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: ~/.venv
          key: ${{ runner.os }}-${{ matrix.python }}-venv-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python }}-venv-

      - name: Cache datasets
        uses: actions/cache@v2
        with:
          path: |
            ~/scikit_learn_data
            ~/river_data
          key: ${{ runner.os }}

      - name: Download datasets
        run: python -c "from river import datasets; datasets.CreditCard().download(); datasets.Elec2().download()"

      - name: pytest
        run: pytest -m "not datasets" --durations=10 -n logical # Run pytest on all logical CPU cores