name: unit-tests

on:
  push:
    branches:
      - main
      - feature/shared_builds

jobs:
  call-build-river:
    uses: ./.github/workflows/build-river.yml

  test:
    runs-on: ${{ matrix.os }}
    needs: call-build-river
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10"]
        os: [ubuntu-latest]

    steps:
      - name: Retrieve the Python environment
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: ~/.venv
          key: ${{ matrix.os }}-${{ matrix.python }}-venv-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.python }}-venv-

#      - name: Retrieve the Python environment
#        uses: actions/cache/save@v3
#        id: cache-venv
#        with:
#          path: |
#            ~/.venv
#            ${{ github.workspace }}
#          key: ${{ matrix.os }}-${{ matrix.python }}-venv-${{ github.run_id }}

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: river-build-${{ github.run_id }}-${{ matrix.os }}-${{ matrix.python }} # Artifacts should only be used within runs!
          path: ~/

      - run: ls -la

#      - name: Extract Venv artifact
#        run: tar -xf ~/venv.tar.gz -C ~/ && ls -la ~/.venv

      - name: Extract River artifact
        run: tar -xf ~/river.tar.gz -C / && ls -la $GITHUB_WORKSPACE

      - name: Cache River datasets
        uses: actions/cache@v2
        with:
          path: ~/river_data
          key: ${{ runner.os }}

      - name: Cache scikit-learn datasets
        uses: actions/cache@v2
        with:
          path: ~/scikit_learn_data
          key: ${{ runner.os }}

      - name: Download datasets
        run: |
          source ~/.venv/bin/activate
          python -c "from river import datasets; datasets.CreditCard().download(); datasets.Elec2().download()"

      - name: pytest
        run: |
          source ~/.venv/bin/activate
          pytest -m "not datasets" --durations=10 -n logical # Run pytest on all logical CPU cores