name: unit-tests

on:
  push:
    branches:
      - main
      - feature/shared_builds

jobs:
  call-build-river:
    uses: ./.github/workflows/build-river.yml

  test:
    runs-on: ${{ matrix.os }}
    needs: call-build-river
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10"]
        os: [ubuntu-latest]

    steps:
      - name: Retrieve the Python environment
        uses: actions/cache/restore@v3
        id: retrieve-venv
        with:
          path: ~/.venv
          key: ${{ github.run_id }}-venv-${{ matrix.os }}-${{ matrix.python }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.python }}-venv

      - name: Retrieve River
        uses: actions/cache/restore@v3
        id: retrieve-river
        with:
          path: ${{ github.workspace }}
          key: river-build-${{ github.run_id }}-${{ matrix.os }}-${{ matrix.python }}

      - name: Cache River datasets
        uses: actions/cache@v2
        with:
          path: |
             ~/scikit_learn_data
             ~/river_data
          key: ${{ runner.os }}-datasets

      - name: Download datasets
        run: |
          source ~/.venv/bin/activate
          python -c "from river import datasets; datasets.CreditCard().download(); datasets.Elec2().download()"

      - name: pytest
        run: |
          source ~/.venv/bin/activate
          pytest -m "not datasets" --durations=10 -n logical # Run pytest on all logical CPU cores